version: '3.8'

services:
  persistence-furthers:
    build: .
    container_name: persistence-furthers
    environment:
      - EVENTSTORE_CONNECTION_STRING=esdb://host.docker.internal:2113?tls=false
      - RABBITMQ_CONNECTION_STRING=amqp://host.docker.internal:5672
      - NODE_ENV=production
    restart: unless-stopped